drop table if exists direction cascade;
drop table if exists usuario cascade ;

create table direction (
    id bigint generated by default as identity,
    user_id UUID,
    citycode varchar(255),
    contrycode varchar(255),
    number varchar(255),
    primary key (id)
);

create table usuario (
    id UUID not null,
    created timestamp(6),
    last_login timestamp(6),
    modified timestamp(6),
    email varchar(255),
    names varchar(255),
    password varchar(255),
    state varchar(255) not null,
    primary key (id)
);

alter table if exists direction
   add constraint FK3r2uew4chwucfov5lx8y2mp0c
   foreign key (user_id)
   references usuario;